export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const FETCH_DETAIL_MOVIE = 'FETCH_DETAIL_MOVIE';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_FAIL = 'FETCH_DETAIL_FAIL';

export const FILTERED_MOVIES = 'FILTERED_MOVIES';